### ISSUE TITLE
Issue with managed workers

### ISSUE THREAD

**Issue by adrwa** [HRZNStudio/Spatial#31]
```Worker EntityWorker8 exited with an error. Exit status: exit status 1.
    exit status 1
Exception in thread "main"
net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
        at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
        at java.lang.SecurityManager.checkExit(Unknown Source)
        at java.lang.Runtime.exit(Unknown Source)
        at java.lang.System.exit(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at com.hrznstudio.spatial.SpatialLaunchWrapper.main(SpatialLaunchWrapper.java:17)```

**Comment by Bluexin** [comment]
That stacktrace is a stupid thing from fml which hides the actual error.
I'll look into it
